name: run linter

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt