name: run linter

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: setup the python version
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: install requirements on the machine
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt