name: run linter

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout to the latest changes
        uses: actions/checkout@v2

      - name: setup the python version
        uses: action/setup-python@v4
        with:
          python-version: 3.10

      - name: black code formatter
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

      - name: install requirements on the machine
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          




